services:
  mysql:
    image: "mysql:8.0"
    volumes:
      - .\\containers\\mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: "mysql"
    volumes:
      - .:/app
  front:
    build: 
      context: ./front
    depends_on:
      - app
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
      NEXT_PUBLIC_URL: "http://localhost:4000"
    volumes:
      - ./front:/app
